version: '3.8'

services:
  ai-tutor-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NESTJS_API_URL=${NESTJS_API_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    restart: unless-stopped